[tox]
minversion = 4

# relies on the correct version of Python installed
# (we rely on CI for the test matrix)
envlist = ruff,tests,mypy,ty

# https://github.com/tox-dev/tox/issues/20#issuecomment-247788333
# hack to prevent .tox from crapping to the project directory
toxworkdir = {env:TOXWORKDIR_BASE:}{toxinidir}/.tox

[testenv]
# TODO how to get package name from setuptools?
package_name = "my"
pass_env =
# useful for tests to know they are running under ci
    CI
    CI_*
# respect user's cache dirs to prevent tox from crapping into project dir
    PYTHONPYCACHEPREFIX
    MYPY_CACHE_DIR
    RUFF_CACHE_DIR

set_env =
# do not add current working directory to pythonpath
# generally this is more robust and safer, prevents weird issues later on
    PYTHONSAFEPATH=1

runner = uv-venv-lock-runner
uv_sync_locked = false

[testenv:ruff]
skip_install = true
dependency_groups = testing
commands =
    {envpython} -m ruff check \
        {posargs}


[testenv:tests]
dependency_groups = testing
set_env =
    {[testenv]set_env}
    # hack similar to MYPYPATH hacking in testenv:mypy
    # otherwise, they have wronth .pth file order and things don't work
    # TODO alternatively, could use reorder_editable?
    PYTHONPATH=src
commands =
    {envpython} -m my.core module install \
        my.orgmode \
        my.time.tz.via_location \
        my.reddit.rexport
    # posargs allow test filtering, e.g. tox ... -- -k test_name
    {envpython} -m pytest \
        --pyargs {[testenv]package_name} \
        # FIXME sort these out later..
        # they are failing due to expecting private config?
        --ignore src/my/util/hpi_heartbeat.py \
        {posargs}


[testenv:mypy]
set_env =
    {[testenv]set_env}
    # somewhat dirty trick to force mypy to check _this_ namespace package
    # otherwise it may end up trying to check 'main' HPI package
    # see https://github.com/python/mypy/issues/16683
    # another option may be to reorder __editable__ paths here..
    MYPYPATH=src
dependency_groups = typecheck
commands =
    {envpython} -m mypy --no-install-types \
        -p {[testenv]package_name}       \
        # txt report is a bit more convenient to view on CI
        --txt-report  .coverage.mypy     \
        --html-report .coverage.mypy     \
        {posargs}


[testenv:ty]
dependency_groups = typecheck
commands =
    {envpython} -m ty \
        check \
        {posargs}
